### ISSUE TITLE
jpm xpi creates empty files

### ISSUE THREAD

**Issue by kiboke** [mozilla-jetpack/jpm#460]
Hello,

My addon has ~2000 css and js files (lazy loaded when needed, don't worry). For some reason when creating xpi file, some files are empty. Size 0.

I have created a new addon with "jpm init" to test, then created 2000 css files and after packing it all with jpm xpi, I can see inside 1014 good css files, others are empty. Changing their content length doesn't have any effect.

While it's possible to add them later manually, the problem exists with "jpm test" as well, so testing doesn't work as expected.

Test addon is attached. Unpack it and run "jpm xpi" to test.

[jpm-bug-test.zip](https://github.com/mozilla-jetpack/jpm/files/79871/jpm-bug-test.zip)

**Comment by wagnerand** [comment]
Just tested this and it works for me just fine on Mac 10.11.2 and and JPM 1.0.3.

What is your operating system and JPM version?

**Comment by kiboke** [comment]
kubuntu 14.04, jpm 1.0.3

**Comment by laurentj** [comment]
Same issue with [the addon I'm working on](https://github.com/laurentj/opquast-desktop). [One module](https://github.com/laurentj/opquast-test-runner) contains thousand files for tests. The xpi file contains about 14060 files (but only about 138 files without tests) . Many of them are empty in the xpi file, and so many tests fail.

If I use the zip command line tool to create a zip : no problem.

Perhaps the issue is in one of the npm lib you use to create the xpi?

jpm: 1.0.4
kubuntu: 15.04

**Comment by kumar303** [comment]
I also can't reproduce it on Mac OS X. Could you attach a copy of your generated `@jpm-bug-test-0.0.1.xpi` so I can see how it created an XPI with empty files? Could you also attach a log of output when you run `jpm --verbose xpi`?

**Comment by kiboke** [comment]
The problem is obviously linux related.

This is my --verbose output (looks good). I can't upload my xpi file (or even a zip file) for some reason. Maybe laurentj will be able to do it.

[output.txt](https://github.com/mozilla-jetpack/jpm/files/97781/output.txt)

**Comment by kumar303** [comment]
[zip-dir](https://github.com/jsantell/node-zip-dir) is behind a version of [js-zip](https://www.npmjs.com/package/jszip) and I see some possibly related bugs [that have been fixed](http://stuk.github.io/jszip/CHANGES.html) in a newer version. So one thing to try is updating `zip-dir` with the latest `js-zip` to see if the bug is fixed.

**Comment by kumar303** [comment]
> So one thing to try...

This would involve opening a pull request in [zip-dir](https://github.com/jsantell/node-zip-dir) with the `js-zip` upgrade, getting a release, then applying a `zip-dir` upgrade to `jpm`. You could test it out locally first if you had all the sources.

**Comment by kiboke** [comment]
I installed jpm with apt-get and there's nothing there to upgrade. I didn't quite understand your upgrade procedure.

**Comment by kumar303** [comment]
The procedure would be involved. I would do it like this:
* Check out jpm from source and install it
* Check out zip-dir from source
* Patch zip-dir to use an upgraded js-zip
* Symlink zip-dir to jpm's node_modules (or maybe some `npm link` tricks will help here)
* See if the error still persists with the upgraded js-zip

**Comment by kiboke** [comment]
Thanks. I manually updated zip-dir and js-zip (I put a console.log() inside just to check if those are in use), but the problem remains.

**Comment by kumar303** [comment]
Ah, bummer. It was worth a try. Thanks for spending the time to test that.

**Comment by kumar303** [comment]
I guess the next step would be to track down the bug, which is presumably happening in js-zip or zip-dir.

**Comment by kiboke** [comment]
in zip-dir/index.js, in function addItem, there's line "fs.readFile(fullPath, function (err, data)"

This "data" argument is undefined for all empty files in the XPI, meaning that compression works fine and reading files fails. I can't find the real location of file containing readFile function, can you help?

**Comment by kiboke** [comment]
I found a solution.

in kubuntu, default max number of open files is 1024. you can check it with ulimit -n
set it with, ie, ulimit -n 4096 (or whatever number suits you. put it in your .bashrc so it is set every time).
jpm xpi will work fine then!

why are those files all open at the same time while reading the directory, i don't know. might be a node.js related bug with async file reading.

**Comment by kumar303** [comment]
oh, I see. Open file limits are the cause of many problems, yes. It would be great if jpm provides an actual error message for this rather than happily creating empty files. I'll leave the bug open to add that feature.

**Comment by kumar303** [comment]
> in zip-dir/index.js, in function addItem, there's line "fs.readFile(fullPath, function (err, data)"

Nice work tracking that down. It looks like the error is [handled here](https://github.com/jsantell/node-zip-dir/blob/master/index.js#L81) but maybe [this call](https://github.com/jsantell/node-zip-dir/blob/master/index.js#L52-L55) to `addItem()` is ignoring it?

**Comment by kumar303** [comment]
> I can't find the real location of file containing readFile function

That's buried in the node library somewhere. The docs are at least here: https://nodejs.org/api/fs.html#fs_fs_readfile_file_options_callback

**Comment by kumar303** [comment]
You could try changing this:

````
addItem(fullPath, function (err) {
  if (!--count) {
    callback(err);
  }
});
````

to:

````
addItem(fullPath, function (err) {
  callback(err);
});
````
to see if that reveals the error.

**Comment by kiboke** [comment]
No error. And the process never finishes.

**Comment by kumar303** [comment]
`¯\_(ツ)_/¯`

weird

**Comment by kiboke** [comment]
I changed zip-dir/index.js so it doesn't open more then X files at once.

At the top of the file I added:
```
var maxOpenFiles = 500;
var openFiles = 0;
```

And changed the fs.readFile part:

```
if (openFiles < maxOpenFiles)
{
  openFiles++;
  fs.readFile(fullPath, function (err, data) {
    if (options.each) {
      options.each(path.join(dir, file));
    }
    folders[dir].file(file, data);
    openFiles--;
    cb(err);
  });
}
else
  addItem (fullPath, cb);
```

It takes a little longer now but works perfectly, no need for setting ulimit.

**Comment by kumar303** [comment]
That sounds like a good fix. Can you open a pull request here? I can help you get it merged. https://github.com/jsantell/node-zip-dir

**Comment by kiboke** [comment]
i'll need some help with the procedure, please contact me (skype: leinad_kindalk) so we can speed it up.

**Comment by kumar303** [comment]
ok, no worries. Maybe I can find some time to apply the patch for you. I'll leave this issue open.

**Comment by kiboke** [comment]
i know how to git clone, create a branch and push changes (i don't have permissions of course). i don't understand pull requests yet, but i'd be happy to do it if you let me know how.

**Comment by kumar303** [comment]
GitHub has [good documentation on creating pull requests](https://help.github.com/articles/creating-a-pull-request/) but it would be a little more involved with that because you'd need to add some tests along with the patch.

**Comment by kiboke** [comment]
I think I got it...

**Comment by kumar303** [comment]
@kiboke thanks for spending time on your patch. I think it's fixed now in the master branch of jpm. Can you try to install it from master with the [git clone... instructions](https://github.com/mozilla-jetpack/jpm/#install) to see if it fixes the issue for you?

**Comment by kiboke** [comment]
I installed it, it works well now. Thank you for your time and help, although I expected someone else will actually debug it, not me :)

**Comment by kumar303** [comment]
Thanks! I run Mac OS so I'd have to set up a Linux VM to test it and I'm lazy, heh. I appreciate the help.
