### ISSUE TITLE
Support non-SDK addons with jpm sign?

### ISSUE THREAD

**Issue by willsALMANJ** [mozilla-jetpack/jpm#465]
Right now, `jpm sign` parses the `package.json` file in order to determine an addon's metadata. In https://github.com/mozilla-jetpack/jpm/pull/456, progress towards parsing `install.rdf` is mentioned (and the error message "These XPIs are not supported yet" was added for non-SDK addons). All that is needed to sign an addon is to parse `install.rdf` for the addon id and version (plus the AMO credentials and `.xpi` file).

Is supporting non-SDK addons something that is planned to be added in the near future, or just something that would be nice to add but with no immediate plans? It is slightly redundant, but I wouldn't mind `jpm sign` working on non-SDK addons by requiring that the addon id and version be passed as command line parameters rather than parsing the `install.rdf` file if that were easier to implement.

For now, I use my own script (https://github.com/willsALMANJ/pentadactyl-signed/blob/master/amo_xpi_sign.py) for signing old XUL addons, but it would be nice to `jpm` instead since it is better tested and maintained.

**Comment by kumar303** [comment]
Non SDK addons will definitely be supported soon, the RDF parsing just
hasn't been implemented yet.

**Comment by willsALMANJ** [comment]
Thanks for the response! I will watch this to know when signing non-SDK addons has been added.

**Comment by kumar303** [comment]
It should be fixed on master. Could you test it out following these [install instructions](https://github.com/mozilla-jetpack/jpm/#install) to see if it works before we publish a release?

**Comment by willsALMANJ** [comment]
Works for me, thanks!

**Comment by kumar303** [comment]
![highfive](https://cloud.githubusercontent.com/assets/55398/12528128/19e34f44-c153-11e5-8fa6-c2170768dd99.gif)

**Comment by meabhi007** [comment]
I am using the installation instructions provided to install JPM using github.
Still getting the error: JPM [error] Server response: Duplicate add-on ID found. ( status: 400 )
Do i need to modify <em:id> tag in install.rdf file to upload the revised version of extension?
Tried changing version in package.json, but it didn't help.

**Comment by kumar303** [comment]
Yes, it looks for `package.json` first then falls back to `install.rdf`. Both need to be up to date with the correct information.
